# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPoorni():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_poorni(self):
    self.driver.get("https://tamilglitz.in/bigg-boss-tamil-vote//bigg-boss-tamil-vote/")
    self.driver.set_window_size(746, 816)
    element = self.driver.find_element(By.CSS_SELECTOR, ".grid-parent > .menu-toggle")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,60.79999923706055)")
    self.driver.find_element(By.CSS_SELECTOR, ".css-answer-group:nth-child(5) .css-answer-span").click()
    self.driver.find_element(By.ID, "pd-vote-button11073604").click()
    self.driver.close()
  
